<a href="https://colab.research.google.com/github/pranav-pragyan/spam-classification/blob/main/Spam_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Approach

##Raw deta --> Number vector --> Machine Learning --> classified output (spam or not)

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd

In [11]:
path = "/content/drive/MyDrive/Colab Notebooks/NLP/spam.csv"
data = pd.read_csv(path)

In [12]:
data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [14]:
data['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [15]:
data['Category'].unique()

array(['ham', 'spam'], dtype=object)

In [16]:
##convert category column to number
data['spam'] = data['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [17]:
data.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(data['Message'], data['spam'], test_size=0.20, random_state=42)

In [20]:
X_train.head()

1978    Reply to win £100 weekly! Where will the 2006 ...
3989    Hello. Sort of out in town already. That . So ...
3935     How come guoyang go n tell her? Then u told her?
4078    Hey sathya till now we dint meet not even a si...
4086    Orange brings you ringtones from all time Char...
Name: Message, dtype: object

In [24]:
X_train[1978][:]

'Reply to win £100 weekly! Where will the 2006 FIFA World Cup be held? Send STOP to 87239 to end service'

In [25]:
y_train[1978]

1

In [26]:
X_train[:4]

1978    Reply to win £100 weekly! Where will the 2006 ...
3989    Hello. Sort of out in town already. That . So ...
3935     How come guoyang go n tell her? Then u told her?
4078    Hey sathya till now we dint meet not even a si...
Name: Message, dtype: object

In [28]:
##convert text to vector using bag of words technique
from sklearn.feature_extraction.text import CountVectorizer

In [80]:
vc = CountVectorizer()

In [81]:
X_train_cv = vc.fit_transform(X_train.values)

In [82]:
type(X_train.values)

numpy.ndarray

In [83]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [84]:
len(X_train_cv.toarray()[1])

7701

In [85]:
len(X_train_cv.toarray())

4457

In [86]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [87]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [88]:
len(X_train_cv.toarray()[:2][0])

7701

In [89]:
X_train_cv.shape

(4457, 7701)

In [90]:
vc.get_feature_names_out()[1000:1050]

array(['anyones', 'anyplaces', 'anythiing', 'anythin', 'anything',
       'anythingtomorrow', 'anytime', 'anyway', 'anyways', 'anywhere',
       'apart', 'apartment', 'apes', 'apeshit', 'apnt', 'apo',
       'apologetic', 'apologise', 'apologize', 'apology', 'app',
       'apparently', 'appeal', 'appear', 'appendix', 'applausestore',
       'applebees', 'apples', 'application', 'apply', 'applyed',
       'applying', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approve', 'approved', 'approx', 'apps', 'appt',
       'appy', 'april', 'aproach', 'apt', 'aquarius', 'ar', 'arab',
       'arabian', 'arcade'], dtype=object)

In [91]:
vc.get_feature_names_out().shape

(7701,)

In [92]:
vocab = vc.vocabulary_

In [93]:
vocab['anyones']

1000

In [94]:
##convert X_train_cv to numpy array
X_train_np = X_train_cv.toarray()

In [95]:
# X_train_np[1].where(X_train_np!=0)
np.where(X_train_np[1]!=0)

(array([ 924,  934, 2395, 2504, 2627, 3369, 3441, 3603, 3926, 4057, 4650,
        4854, 4976, 5825, 6252, 6304, 6770, 6959, 7471, 7662]),)

###ML Model

In [96]:
## import ML model : Naive Bayes 
from sklearn.naive_bayes import MultinomialNB

In [97]:
model = MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

###Testing and model evaluation


In [98]:
X_test_cv = vc.transform(X_test)

In [99]:
from sklearn.metrics import classification_report

In [100]:
y_pred = model.predict(X_test_cv)

In [101]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       966
           1       1.00      0.94      0.97       149

    accuracy                           0.99      1115
   macro avg       1.00      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [102]:
emails = [ 'Hey mohan, can we get together to watch footbal game tomorrow?', 'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!']

In [104]:
email_cv = vc.transform(emails)

In [105]:
model.predict(email_cv)

array([0, 1])

###Doing the classification using Sklearn Pipeline

In [106]:
from sklearn.pipeline import Pipeline

In [107]:
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb',MultinomialNB())
])

In [108]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [109]:
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       966
           1       1.00      0.94      0.97       149

    accuracy                           0.99      1115
   macro avg       1.00      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

